=== hanzhangzhao/XML-resume/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="resume">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="nameType"/>
				<xs:element name="address" type="addressType"/>
				<xs:element name="contact" type="contactType"/>
				<xs:element name="bodypart" type="bodypartType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="nameType">
		<xs:sequence>
			<xs:element name="firstname" type="xs:string"/>
			<xs:element name="lastname" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="province" type="xs:string"/>
			<xs:element name="zipcode" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="contactType">
		<xs:sequence>
			<xs:element name="phone" type="xs:integer"/>
			<xs:element name="email" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="bodypartType">
		<xs:sequence>
			<xs:element name="education" type="educationType"/>
			<xs:element name="skills" type="skillsType"/>
			<xs:element name="projects" type="projectsType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="educationType">
		<xs:sequence>
			<xs:element name="degree" type="degreeType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="degreeType">
		<xs:sequence>
			<xs:element name="program" type="xs:string"/>
			<xs:element name="major" type="xs:string"/>
			<xs:element name="duration" type="durationType"/>
			<xs:element name="university" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="province" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="durationType">
		<xs:sequence>
			<xs:element name="startdate" type="xs:gYearMonth"/>
			<xs:element name="enddate" type="xs:gYearMonth"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="skillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="skillType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="Database"/>
							<xs:enumeration value="OS"/>
							<xs:enumeration value="Programming"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="projectsType">
		<xs:sequence>
			<xs:element name="project" type="projectType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="projectType">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="description" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="province">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="MB"/>
				<xs:enumeration value="Manitoba"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
</xs:schema>

=== hanzhangzhao/XML-resume/resume.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type = "text/xsl" href = "resume.xsl"?>
<!-- Personal resume marked up with XML -->
<resume xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\hazen\Desktop\resume.xsd">
	<name>
		<firstname>Hanzhang</firstname>
		<lastname>Zhao</lastname>
	</name>
	<address>
		<street>172 Bridgeland Dr</street>
		<city>Winnipeg</city>
		<province>MB</province>
		<zipcode>R3Y0E2</zipcode>
	</address>
	<contact>
		<phone>2042309805</phone>
		<email>hazenzhao@gmail.com</email>
	</contact>
	<bodypart>
		<education>
			<degree>
				<program>Bachelor of Science</program>
				<major>Computer Science major</major>
				<duration>
					<startdate>2015-09</startdate>
					<enddate>2019-05</enddate>
				</duration>
				<university>University of Manitoba</university>
				<city>Winnipeg</city>
				<province>Manitoba</province>
			</degree>
			<degree>
				<program>Bachelor of Science</program>
				<major>Electrical Engineering major</major>
				<duration>
					<startdate>2013-01</startdate>
					<enddate>2015-09</enddate>
				</duration>
				<university>University of Manitoba</university>
				<city>Winnipeg</city>
				<province>Manitoba</province>
			</degree>
		</education>
		<skills>
			<skill name="Programming">
        HTML5, CSS3, JavaScript, PHP, C#, Java, Python, C++, C, LC3 Assemble, Ruby
      </skill>
			<skill name="Database">
        MySQL, MariaDB, SQL
      </skill>
			<skill name="Library/Technology">
        Ajax, Bootstrap, jQuery, Socket.IO, XML, WordPress, ASP.NET, git, GCP
      </skill>
      <skill name="Operating System">
        Windows, Unix, Linux, Mac OS X
      </skill>
		</skills>
		<projects>
			<project>
				<title>E-commerce website (HTML, CSS, JavaScript, PHP)</title>
				<description>
          -	Built an ecommerce website using HTML, CSS, and Bootstrap
        </description>
        <description>
          -	Implemented a user authentication system including graphic captcha by JavaScript and PHP
        </description>
        <description>
          -	Installed and configured LAMP solution in Ubuntu environment
        </description>
			</project>
			<project>
				<title>ASP.NET online computer store (C#, ASP.NET)</title>
				<description>
          -	Developed an online computer store using ASP.NET in C# as server-side language
        </description>
        <description>
          -	Designed and built a database to store product information and user credentials by MySQL
        </description>
        <description>
          -	The web application was published to Azure App Service using Visual Studio
        </description>
        <description>
          -	Customers are able to customize the hardware of a pre-built computer based on their needs
        </description>
			</project>
      <project>
				<title>Food ordering system (jQuery)</title>
				<description>
          -	Collaborated with two members to designed and implemented the menu by HTML and CSS
          -	Independently Implemented place, edit, and delete order function using jQuery and JavaScript
          -	HCI techniques, such as identify stakeholders, brainstorm, usability testing, and paper prototypes are used in application development process
        </description>
        <description>
          -	Customers are able to customize the hardware of a pre-built computer based on their needs
        </description>
        <description>
          -	Customers are able to customize the hardware of a pre-built computer based on their needs
        </description>
			</project> 
			<project>
				<title>Tetris Game (WebSocket)</title>
				<description>
          -	Built a WebSocket server by using node.js WebSocket module in localhost      
        </description>
        <description>
          -	Implemented 2-player mode, which 2 players can play against one another on the same computer, by socket.IO library
        </description>
        <description>
          -	The user interface and game pieces are built by HTML, CSS, and JavaScript
        </description>
			</project>
      <project>
				<title>Utility tools (Ajax, JavaScript)</title>
				<description>
          -	Designed and developed some useful utility tools including measurement converters, mortgage calculator, currency exchanger, etc
        </description>
        <description>
          -	Ajax technologies are used to eliminate whole page update when switching from one utility tool to another
        </description>
			</project>
		</projects>
	</bodypart>
</resume>
